#!/usr/bin/env node
/**
 * Regenerates `renderer/src/lib/cambodia-grid.ts`.
 *
 * Pipeline:
 *   1. Fetch Natural Earth 1:10m admin-0 countries (CC0 / public domain).
 *   2. Pick the Cambodia (KHM) feature, normalise to a MultiPolygon.
 *   3. Buffer outward by a small distance so coastal grid cells over the
 *      Gulf of Thailand and Tonle Sap's edges are kept (the PRD calls for
 *      "land and water extent" — coastal waters are included).
 *   4. Walk the 0.25° bounding-box grid; keep every point inside the buffer.
 *   5. Write the resulting array to `cambodia-grid.ts` as `as const`.
 *
 * The Natural Earth GeoJSON is downloaded fresh each run and NOT committed
 * to the repo (it's ~30 MB). Only the generated TS file ships in git.
 *
 * Run with:  node scripts/build-grid.mjs
 */

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import buffer from '@turf/buffer';
import booleanPointInPolygon from '@turf/boolean-point-in-polygon';
import { point } from '@turf/helpers';

const NE_COUNTRIES_URL =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson';

/** 0.5° grid step (~55 km). Was 0.25° initially but the resulting 289-point
 * grid carpeted the country at country zoom and the icons were too small to
 * read. 0.5° lands around ~70 points after masking — closer to the PRD's
 * "approximately 100" estimate and gives each icon room to breathe. */
const GRID_STEP_DEG = 0.5;

/** Cambodia bounding box (from the PRD; tightened to half-step alignment). */
const LAT_MIN = 10.5;
const LAT_MAX = 14.75;
const LON_MIN = 102.25;
const LON_MAX = 107.75;

/** Outward buffer to include coastal waters & near-border cells (in km). */
const COASTAL_BUFFER_KM = 15;

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TS_OUTPUT_PATH = resolve(REPO_ROOT, 'renderer/src/lib/cambodia-grid.ts');
const RUST_OUTPUT_PATH = resolve(REPO_ROOT, 'src-tauri/src/cambodia_grid.rs');

async function main() {
  process.stdout.write(`Fetching Natural Earth admin-0 countries…\n`);
  const response = await fetch(NE_COUNTRIES_URL);
  if (!response.ok) {
    throw new Error(`Natural Earth fetch failed: HTTP ${response.status}`);
  }
  const collection = await response.json();
  process.stdout.write(`  → ${collection.features.length} countries\n`);

  // Natural Earth's country-code field is `ADM0_A3`. KHM = Cambodia.
  const cambodia = collection.features.find(
    (feature) => feature?.properties?.ADM0_A3 === 'KHM'
  );
  if (!cambodia) {
    throw new Error('Cambodia (ADM0_A3=KHM) not found in Natural Earth countries.');
  }

  process.stdout.write(`Buffering polygon outward by ${COASTAL_BUFFER_KM} km…\n`);
  const buffered = buffer(cambodia, COASTAL_BUFFER_KM, { units: 'kilometers' });

  process.stdout.write(`Walking ${LAT_MIN}–${LAT_MAX}°N × ${LON_MIN}–${LON_MAX}°E at ${GRID_STEP_DEG}°…\n`);
  const grid = [];
  // Floating-point drift in additive loops produces 102.50000000000001 — keep
  // a step counter and reconstruct each axis with a multiplication to avoid it.
  const latCount = Math.round((LAT_MAX - LAT_MIN) / GRID_STEP_DEG) + 1;
  const lonCount = Math.round((LON_MAX - LON_MIN) / GRID_STEP_DEG) + 1;
  for (let i = 0; i < latCount; i++) {
    const lat = round2(LAT_MIN + i * GRID_STEP_DEG);
    for (let j = 0; j < lonCount; j++) {
      const lon = round2(LON_MIN + j * GRID_STEP_DEG);
      if (booleanPointInPolygon(point([lon, lat]), buffered)) {
        grid.push({ lat, lon });
      }
    }
  }
  process.stdout.write(`  → kept ${grid.length} grid points\n`);

  writeFileSync(TS_OUTPUT_PATH, renderTypeScript(grid));
  process.stdout.write(`Wrote ${TS_OUTPUT_PATH}\n`);
  writeFileSync(RUST_OUTPUT_PATH, renderRust(grid));
  process.stdout.write(`Wrote ${RUST_OUTPUT_PATH}\n`);
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

function renderTypeScript(grid) {
  const rows = grid
    .map(({ lat, lon }) => `  { lat: ${lat.toFixed(2)}, lon: ${lon.toFixed(2)} }`)
    .join(',\n');

  return `// AUTO-GENERATED by scripts/build-grid.mjs — do not edit by hand.
// To regenerate:  node scripts/build-grid.mjs
//
// Source: Natural Earth 1:10m admin-0 countries (public domain), buffered
// outward by ${COASTAL_BUFFER_KM} km so coastal grid cells (Gulf of Thailand) are
// included. ${grid.length} points at ${GRID_STEP_DEG}° resolution covering
// Cambodia's land and immediate coastal waters.

export interface GridPoint {
  readonly lat: number;
  readonly lon: number;
}

export const CAMBODIA_GRID: readonly GridPoint[] = [
${rows}
] as const;
`;
}

function renderRust(grid) {
  const rows = grid
    .map(({ lat, lon }) => `    (${lat.toFixed(2)}, ${lon.toFixed(2)})`)
    .join(',\n');

  return `// AUTO-GENERATED by scripts/build-grid.mjs — do not edit by hand.
// To regenerate:  node scripts/build-grid.mjs
//
// Must stay in lock-step with renderer/src/lib/cambodia-grid.ts. The
// forecast_grid Tauri command sends these (lat, lon) pairs to Open-Meteo
// in this exact order; the renderer pairs the response back to the TS
// grid by index, so any drift between the two arrays surfaces immediately
// as a length-mismatch error in the hook.

/// (latitude, longitude) for every Cambodia 0.25° grid point.
pub const CAMBODIA_GRID: [(f64, f64); ${grid.length}] = [
${rows},
];
`;
}

main().catch((err) => {
  process.stderr.write(`build-grid failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
